### ISSUE TITLE
Need to resolve the routing in app and project urls.py files

### ISSUE THREAD

**Issue by yokwejuste** [Wise-view/devtoy#16]
## Introduction
Going through your changes, it's awesome the rate of learning. I really do appreciate that. But some minor points I've to raise here.

## Issues
- The routing of an app in the main urls.py is done as follows:
     - Create a new field in the urls_patterns, it should look like this:
     ```python
           from ... import .... path, include
            urls_pattern = [
                         path('admin', ......), 
                         path(' ', include('appname.urls')
               ]
- Then all your paths functions should be referenced in your urls.py.
- Guys (@AtudJerry and @Fotsingboris ) please work on this today.

**Comment by AtudJerry** [comment]
- Sir @yokwejuste  we have already configured all the urls.py files with the path correctly
